### 
GET http://localhost:3000/api/v1/penghuni

###
GET backend-accessapp.vercel.app/api/v1/penghuni

### 
GET http://localhost:3000/api/v1/pengunjung/663dc636f5ee747f584b3b22
###
GET http://localhost:3000/api/v2/pengunjung
###
POST http://localhost:3000/api/v1/pengunjung
Content-Type: application/json

{
   "name": "budi",
   "penghuniId": "663c5194991625b77ad755df",
   "kepentingan": "paket"
}

###
PUT http://localhost:3000/api/v2/pengunjung/664059450e0349a54ad450f5
Content-Type: application/json

{
   "status": "akses diterima"
}

###
POST http://localhost:3000/api/v2/register
Content-Type: application/json

{
    "email": "Harmon@gmail.com",
    "alamat": "L-23",
    "name": "harmon",
    "password": "harmon",
    "isAdmin": false,
    "isVeryfied": false
}

### 
GET http://localhost:3000/api/v1/penghuni/663da56bf5ee747f584b3b14


